// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhzmpwvyvoelimgqefhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoem1wd3Z5dm9lbGltZ3FlZmhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQwNDkyMDUsImV4cCI6MjA0OTYyNTIwNX0.dUPbCnxvV_NonFb0hP3R6CHipqJTmTNf0ZqsmKj-GrE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);